Use Path.GetFullPath() to resolve the full path of the input path.
serilog/serilog-sinks-file pull request #258
Opened 2022-06-29 03:17 UTC by AraHaan

Note: I also changed a few string == null checks to call string.IsNullOrEmpty() so that empty strings also throw (as I think those are error cases as well).

Fixes https://github.com/serilog/serilog-sinks-file/issues/257.

2022-06-29 03:29 UTC, AraHaan commented on src/Serilog.Sinks.File/FileLoggerConfigurationExtensions.cs
> +            var fullPath = Path.GetFullPath(path);
```suggestion
            var fullPath = path;
            if (!Path.IsPathFullyQualified(path))
                fullPath = Path.GetFullPath(path);
```

2022-06-29 03:35 UTC, AraHaan commented on src/Serilog.Sinks.File/FileLoggerConfigurationExtensions.cs
> +            var fullPath = Path.GetFullPath(path);
```suggestion
```

2022-06-29 03:35 UTC, AraHaan commented on src/Serilog.Sinks.File/FileLoggerConfigurationExtensions.cs
> +                    sink = new RollingFileSink(fullPath, formatter, fileSizeLimitBytes, retainedFileCountLimit, encoding, buffered, shared, rollingInterval, rollOnFileSizeLimit, hooks, retainedFileTi
```suggestion
                    sink = new RollingFileSink(path, formatter, fileSizeLimitBytes, retainedFileCountLimit, encoding, buffered, shared, rollingInterval, rollOnFileSizeLimit, hooks, retainedFileTimeLimit);
```

2022-06-29 03:35 UTC, AraHaan commented on src/Serilog.Sinks.File/FileLoggerConfigurationExtensions.cs
> +                        sink = new SharedFileSink(fullPath, formatter, fileSizeLimitBytes, encoding);
```suggestion
                        sink = new SharedFileSink(path, formatter, fileSizeLimitBytes, encoding);
```

2022-06-29 03:35 UTC, AraHaan commented on src/Serilog.Sinks.File/FileLoggerConfigurationExtensions.cs
> +                        sink = new FileSink(fullPath, formatter, fileSizeLimitBytes, encoding, buffered, hooks);
```suggestion
                        sink = new FileSink(path, formatter, fileSizeLimitBytes, encoding, buffered, hooks);
```

2022-06-29 03:35 UTC, AraHaan commented on src/Serilog.Sinks.File/FileLoggerConfigurationExtensions.cs
> +                SelfLog.WriteLine("Unable to open file sink for {0}: {1}", fullPath, ex);
```suggestion
                SelfLog.WriteLine("Unable to open file sink for {0}: {1}", path, ex);
```

2022-06-29 04:22 UTC, AraHaan commented
On Merge please squash this to a single commit that matches the new name for this PR.

2022-06-29 23:16 UTC, nblumhardt commented
Thanks for the PR!

`== null` is the correct intended check in most of these places; where we are accepting file names, if we use `string.IsNullOrEmpty()` we should switch to throwing `ArgumentException` rather than `ArgumentNullException`.

2022-06-30 04:29 UTC, AraHaan commented
Alright, will do.

2022-06-30 04:31 UTC, AraHaan reviewed
Might have to update tests a little after this change.

2022-06-30 04:31 UTC, AraHaan commented on src/Serilog.Sinks.File/FileLoggerConfigurationExtensions.cs
> +            if (string.IsNullOrEmpty(outputTemplate)) throw new ArgumentNullException(nameof(outputTemplate));
```suggestion
            if (string.IsNullOrEmpty(path)) throw new ArgumentException(nameof(path));
            if (string.IsNullOrEmpty(outputTemplate)) throw new ArgumentException(nameof(outputTemplate));
```

2022-06-30 04:31 UTC, AraHaan commented on src/Serilog.Sinks.File/FileLoggerConfigurationExtensions.cs
> +            if (string.IsNullOrEmpty(path)) throw new ArgumentNullException(nameof(path));
```suggestion
            if (string.IsNullOrEmpty(path)) throw new ArgumentException(nameof(path));
```

2022-06-30 04:31 UTC, AraHaan commented on src/Serilog.Sinks.File/FileLoggerConfigurationExtensions.cs
> +            if (string.IsNullOrEmpty(outputTemplate)) throw new ArgumentNullException(nameof(outputTemplate));
```suggestion
            if (string.IsNullOrEmpty(path)) throw new ArgumentException(nameof(path));
            if (string.IsNullOrEmpty(outputTemplate)) throw new ArgumentException(nameof(outputTemplate));
```

2022-06-30 04:31 UTC, AraHaan commented on src/Serilog.Sinks.File/FileLoggerConfigurationExtensions.cs
> +            if (string.IsNullOrEmpty(path)) throw new ArgumentNullException(nameof(path));
```suggestion
            if (string.IsNullOrEmpty(path)) throw new ArgumentException(nameof(path));
```

2022-06-30 04:31 UTC, AraHaan commented on src/Serilog.Sinks.File/FileLoggerConfigurationExtensions.cs
> +            if (string.IsNullOrEmpty(path)) throw new ArgumentNullException(nameof(path));
```suggestion
            if (string.IsNullOrEmpty(path)) throw new ArgumentException(nameof(path));
```

2023-09-28 04:37 UTC, nblumhardt requested changes

2023-09-28 04:37 UTC, nblumhardt commented on src/Serilog.Sinks.File/FileLoggerConfigurationExtensions.cs
> +            // check if null or empty on these.
Redundant comment

2023-09-28 04:37 UTC, nblumhardt commented on src/Serilog.Sinks.File/FileLoggerConfigurationExtensions.cs
> +            if (string.IsNullOrEmpty(outputTemplate)) throw new ArgumentException(nameof(outputTemplate));
An empty output template is fine, the original check was correct here.

2023-09-28 04:37 UTC, nblumhardt commented on src/Serilog.Sinks.File/FileLoggerConfigurationExtensions.cs
> +            if (string.IsNullOrEmpty(outputTemplate)) throw new ArgumentException(nameof(outputTemplate));
An empty output template is fine, the original check was correct here.

2023-10-19 09:03 UTC, bartelink commented
Hi @AraHaan  I'm [doing some spring cleaning here](https://github.com/serilog/serilog-sinks-file/pull/263#issuecomment-1770367986)

If you're intending to resolve the issues and take this PR to it's conclusion, it'd be good to get things resolved sooner than later 

If you don't have capacity to do that in the short to medium term, can I request that this gets closed and then revisited from first principles

In general my review would align what's gone so far - having `null` checks is great; conflating `null` vs `Empty` vs whitespace is pretty much always bad news

2023-10-19 12:17 UTC, AraHaan commented
I will look into this later on either today or tomorrow in order to get this resolved as soon as possible.

2023-10-24 18:05 UTC, AraHaan commented
Sorry about the late response, will get ready for some progress later on today.

2023-10-25 10:19 UTC, AraHaan commented on src/Serilog.Sinks.File/FileLoggerConfigurationExtensions.cs
> +            // check if null or empty on these.
```suggestion
```

2023-10-25 10:19 UTC, AraHaan commented on src/Serilog.Sinks.File/FileLoggerConfigurationExtensions.cs
> +            if (string.IsNullOrEmpty(outputTemplate)) throw new ArgumentException(nameof(outputTemplate));
```suggestion
            if (outputTemplate == null) throw new ArgumentNullException(nameof(outputTemplate));
```

2023-10-25 10:19 UTC, AraHaan commented on src/Serilog.Sinks.File/FileLoggerConfigurationExtensions.cs
> +            if (string.IsNullOrEmpty(outputTemplate)) throw new ArgumentException(nameof(outputTemplate));
```suggestion
            if (outputTemplate == null) throw new ArgumentNullException(nameof(outputTemplate));
```

2023-10-25 10:21 UTC, AraHaan commented
Sorry for being late again, something came up and I had to do that before making the changes here.

2023-10-25 10:29 UTC, bartelink commented on src/Serilog.Sinks.File/FileLoggerConfigurationExtensions.cs
> +            if (string.IsNullOrEmpty(path)) throw new ArgumentException(nameof(path));
this and others invalidates the comments:
```
<exception cref="ArgumentNullException">When <paramref name="path"/> is <code>null</code>
```

2023-10-25 10:31 UTC, AraHaan commented on src/Serilog.Sinks.File/FileLoggerConfigurationExtensions.cs
> +            if (string.IsNullOrEmpty(path)) throw new ArgumentException(nameof(path));
Alright, will fix the comments as soon as possible.

2023-10-25 10:43 UTC, bartelink commented on src/Serilog.Sinks.File/FileLoggerConfigurationExtensions.cs
> +            if (string.IsNullOrEmpty(path)) throw new ArgumentException(nameof(path));
I personally think it would be useful for the existing check and comment to remain as-is for clarity
That way, there's no ambiguity as to what can cause the ArgumentException
(I also wonder if there should be a message indicating that the constraint is that Empty is not permitted and/or the xmldoc should mention it? Right now you're handed an exception and the only reasonable way to figure out the constraint is to read the source?)

2023-10-25 10:50 UTC, bartelink commented
> Sorry for being late again, something came up and I had to do that before making the changes here.

That's absolutely not a problem - the most important thing is that the code and user experience remains as boring as possible. Please take as much time as you want or need; nobody is tied to any date. (The reason I asked for the state is to simply figure out whether it was on the road to being abandoned, or the road to completion)

> Although I feel that output template check code could be optimized further to something like this:

I'm not understanding your reasoning. The current code:

    if (outputTemplate == null) throw new ArgumentNullException(nameof(outputTemplate));

Is clear and unambiguous - you MUST supply an output template. The point is not about efficiency, but clarity.
Silently replacing a critical input with one that makes it silently write nothing would be very susrising and annoying to my mind.

Am I missing something?

2023-10-25 10:59 UTC, bartelink commented
Sorry to be a pain, but following up on https://github.com/serilog/serilog-sinks-file/pull/258#issuecomment-1770399131

- Issue #257, the original motivation for this is now closed.
- This leaves us without an overview comment that explains why this is happening/needed in the first instance

Can you explain in short (ideally in the overview in a clear way for everyone) and/or an extended reason down here why this check is required?

i.e. while a path of `""` will mean files get named `".log`, `"001.log"`, which is wierd, does something more interesting actually go wrong?

- how would the situation arise, other than someone's config file having an empty value? 
- even if that did arise, would it really be bad for them to end up with the strange name the asked on a garbage in- garbage out basis?

In general, the main concern for me is `null` values - empty is just a short string. i.e. if you were accepting a count, then `0` might be a perfectly legitimate value that can just be treated like any other integer?

2023-10-25 19:33 UTC, AraHaan commented
It was originally about fixing that issue, but then I realized a simple misconfiguration of the logging config file resulted in the path not properly being used then closed that issue, but left this pr up as I also noticed that rejecting empty path values can be made as inputting an empty string can result in an exception when it tries to use file I/O to write the logs (it would actually try to write to a file with no name and no file extension and fail).

2024-02-22 01:15 UTC, bartelink commented
Sounds like t[hings are stirring around here](https://github.com/serilog/serilog-sinks-file/issues/177#issuecomment-1958443072)...
So am I to take it that the best thing here is to abandon this PR and see if anynoe runs into similar, or it's not such a big problem after all ?

2024-06-19 12:06 UTC, nblumhardt commented
Closing this one as stale, but thanks for taking the time to check this out 👍

2024-06-19 12:06 UTC, closed without merging